[env:bluephill_F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube
upload_protocol = stlink
build_src_filter = +<Core/Src/>
build_flags = 
    -Isrc/Core/Inc
    -Isrc/Core/Src