[platformio]
src_dir = cubemx/Core/Src
include_dir = cubemx/Core/Inc

[env:bluephill_F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube
upload_protocol = stlink
#upload_flags = -c set CPUTAPID 0x2ba01477
build_src_filter = +<*> -<EWARM>

