[env:bluephill_F103C8]

platform = ststm32
board = genericSTM32F103C8
framework = stm32cube

monitor_speed = 115200
upload_protocol = stlink

build_src_filter =
    +<Core/Src/>
    +<Application/>
    +<Implemented_Drivers/Temperature_Sensor/>
    +<Implemented_Drivers/UART/>
    +<Implemented_Drivers/ADC/>
    +<Implemented_Drivers/Communication/>

build_flags =
    -Isrc/Core/Inc
    -Isrc/Core/Src
    -Isrc/Application
    -Isrc/Implemented_Drivers/Temperature_Sensor
    -Isrc/Implemented_Drivers/UART
    -Isrc/Implemented_Drivers/ADC
    -Isrc/Implemented_Drivers/Communication
    -Wl,-u,_printf_float

test_ignore =
    test_temperature_sensor

[env:native]

platform = native
test_framework = unity
test_build_src = true

build_flags =
    -Isrc/Implemented_Drivers/Temperature_Sensor
    -Isrc/Implemented_Drivers/ADC

build_src_filter =
    +<Implemented_Drivers/Temperature_Sensor/temperature_sensor.c>
